#!/bin/bash
useCase="Useage: manage-website [create|remove|restore] [WEBSITE_NAME]"
if [ 0 -ne "$EUID" ]; then
	echo "You are not root! Exiting!"
	exit 1
fi
if [ "$1" == "create" ] || [ "$1" == "remove" ] || [ "$1" == "restore" ]; then
	if  [ -z "$2" ]; then
		echo $useCase
		exit 1
	fi
	if [ "$1" == "create" ]; then
		exist=$(check-website $2)
		if [ "$exist" == "true" ]; then
			echo "Website already exists! \"Run manage-website remove $2\" to fix this issue"
			exit 1
		fi
		echo "Create "$2"? (yes/no)"
		read confirm
		if [ "$confirm" == "yes" ]; then
			#do website stuff
			mkdir /var/www/$2
			cp "/etc/apache2/sites-available/template.conf" "/etc/apache2/sites-available/$2.conf"
			sed -i "s/template/$2/g" "/etc/apache2/sites-available/$2.conf"
			ln -s "/etc/apache2/sites-available/$2.conf" "/etc/apache2/sites-enabled/$2.conf"
		else
			echo "Cancel!"
		fi
	fi
	if [ "$1" == "remove" ]; then
		echo "REMOVE "$2"?"
		read confirm
		if [ "$confirm" == "yes" ]; then
		#	echo "Removing!"
			mv "/etc/apache2/sites-available/$2.conf" "/etc/apache2/backups/$2.conf" 2> "/dev/null"
			rm "/etc/apache2/sites-enabled/$2.conf" 2> "/dev/null"
			mv "/var/www/$2" "/var/backups/websites/" 2> "/dev/null"
		else
			echo "Cancel!"
		fi
	fi
	if [ "$1" == "restore" ]; then
		mv "/var/backups/websites/$2" "/var/www/"
		mv "/etc/apache2/backups/$2.conf" "/etc/apache2/sites-available/$2.conf"
		ln -s "/etc/apache2/sites-available/$2.conf" "/etc/apache2/sites-enabled/$2.conf"
	fi
	service apache2 reload
else
	echo $useCase
fi
